package com.snail.wms.dao;

import com.snail.wms.entity.SysUserRoleExample;
import com.snail.wms.entity.SysUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int countByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int deleteByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int deleteByPrimaryKey(SysUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int insert(SysUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int insertSelective(SysUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    List<SysUserRoleKey> selectByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUserRoleKey record, @Param("example") SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Fri Feb 01 09:47:03 CST 2019
     */
    int updateByExample(@Param("record") SysUserRoleKey record, @Param("example") SysUserRoleExample example);
}